[default]
LOG_LEVEL = "DEBUG"
# Database pool
POOL_SIZE = 15
POOL_MAX_OVERFLOW = 25
POOL_TIMEOUT = 30
POOL_RECYCLE = 1800
POOL_PRE_PING = true
# S3
S3_BUCKET_NAME = ""
# PDF
WKHTMLTOPDF_PATH = "/usr/local/bin/wkhtmltopdf"
# Security
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 1440

[development]
LOG_LEVEL = "DEBUG"
# Database pool
POOL_SIZE = 15
POOL_MAX_OVERFLOW = 25
POOL_TIMEOUT = 30
POOL_RECYCLE = 1800
POOL_PRE_PING = true
# S3
S3_BUCKET_NAME = "invoicer-dev-01"
# PDF
WKHTMLTOPDF_PATH = "/usr/local/bin/wkhtmltopdf"
# Security
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 1440

[production]
LOG_LEVEL = "INFO"
# Database pool
POOL_SIZE = 15
POOL_MAX_OVERFLOW = 25
POOL_TIMEOUT = 30
POOL_RECYCLE = 1800
POOL_PRE_PING = true
# S3
S3_BUCKET_NAME = "invoicer-files-dev"
# PDF
WKHTMLTOPDF_PATH = "/usr/bin/wkhtmltopdf"
# Security
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 1440
